import type { User, Prompt, JournalEntry, BoardComment, Plan, FeedPost } from './types'

export const currentUser: User = {
  id: 'u1',
  name: 'Sarah M.',
  email: 'sarah@example.com',
  role: 'reader',
  joinedAt: '2026-01-12',
  streak: 7,
  totalEntries: 23,
  bio: 'Learning to ask well.',
}

export const authorUser: User = {
  id: 'author',
  name: 'The Author',
  email: 'author@thewayofasking.com',
  role: 'author',
  joinedAt: '2025-11-01',
  streak: 90,
  totalEntries: 142,
  bio: 'Writer, wonderer, still learning to ask.',
}

export const weeklyPrompts: Prompt[] = [
  {
    id: 'wp1',
    week: 1,
    title: 'Have you started imagining again?',
    body: 'Have you started imagining again?\n\nWhat if imagination isn\'t something we lose, but something that falls asleep? Think about the last time you let yourself imagine something freely — not a plan, not a goal, but a genuine "what if." What did it feel like? What put it to sleep, and what might wake it back up?',
    quote: 'What if imagination isn\'t something we lose, but something that falls asleep?',
    publishAt: '2026-06-01',
    tags: ['imagination', 'dreaming', 'renewal'],
  },
  {
    id: 'wp2',
    week: 2,
    title: 'Have you given yourself permission to dream?',
    body: 'Have you given yourself permission to dream?\n\nSomewhere along the way, a lot of us started asking smaller. We learned to be "realistic." We started editing before we even began. What would it look like to give yourself full permission — even just for one page, one entry — to dream without the footnotes?',
    quote: 'Maybe the goal was never to be remembered forever… maybe it was to live well right now.',
    publishAt: '2026-06-08',
    tags: ['permission', 'dreams', 'freedom'],
  },
  {
    id: 'wp3',
    week: 3,
    title: 'Write to your 18-year-old self.',
    body: 'Write to your 18-year-old self.\n\nWhat do you wish you could tell them about asking? About what was worth worrying over and what wasn\'t? What do you know now that you couldn\'t have known then — and what did that younger version of you understand that you might have forgotten?',
    publishAt: '2026-06-15',
    tags: ['letter', 'reflection', 'younger self'],
  },
  {
    id: 'wp4',
    week: 4,
    title: 'How do we become more rooted in the ground we stand on?',
    body: 'How do we become more rooted in the ground we stand on?\n\nThe way a cloud stretches across the sky, the way spring green returns to the trees and the grass — they remind us that God is always moving, always creating, always restoring. Where do you feel most grounded? What does it take for you to get there?',
    quote: 'The way a cloud stretches across the sky, the way spring green returns to the trees… remind me that God is always moving.',
    publishAt: '2026-06-22',
    tags: ['rootedness', 'nature', 'presence'],
  },
]

export const chapterPrompts: Prompt[] = [
  {
    id: 'cp1',
    week: 0,
    chapter: 1,
    planId: 'main-plan',
    title: 'Chapter 1 — When You Received More Than You Asked For',
    body: 'Reflect on a time you asked for something and received more than you expected.\n\nNot the polished version — the real one. What did you actually ask for? What showed up instead? And looking back, what does that tell you about the nature of asking itself?',
    publishAt: '2026-01-01',
    tags: ['receiving', 'grace', 'asking'],
  },
  {
    id: 'cp2',
    week: 0,
    chapter: 2,
    planId: 'main-plan',
    title: 'Chapter 2 — The Dream You Quietly Put Down',
    body: 'What\'s one dream you quietly gave up on — and what would it look like to pick it back up?\n\nNot the dramatic surrender, but the slow one. The one where you just stopped mentioning it. When did that happen? What would it cost you to bring it back up? What would it cost you if you never did?',
    quote: 'What if imagination isn\'t something we lose, but something that falls asleep?',
    publishAt: '2026-01-01',
    tags: ['dreams', 'letting go', 'courage'],
  },
  {
    id: 'cp3',
    week: 0,
    chapter: 3,
    planId: 'main-plan',
    title: 'Chapter 3 — A Letter to the One You Were',
    body: 'Write a letter to your 18-year-old self. What do you wish someone had told you about asking?\n\nAbout what it means to want things. About the difference between asking out of fear and asking out of trust. What would that younger version of you have needed to hear?',
    publishAt: '2026-01-01',
    tags: ['letter', 'younger self', 'growth'],
  },
  {
    id: 'cp4',
    week: 0,
    chapter: 4,
    planId: 'main-plan',
    title: 'Chapter 4 — Where the Imagining Stopped',
    body: 'Where in your life have you stopped imagining? What would it cost to start again?\n\nBe honest about where the lights have gone a little dim. A relationship. A calling. A hope you carry quietly. What made you stop? And somewhere underneath the "why" — is there still a flicker?',
    publishAt: '2026-01-01',
    tags: ['imagination', 'hope', 'honesty'],
  },
  {
    id: 'cp5',
    week: 0,
    chapter: 5,
    planId: 'main-plan',
    title: 'Chapter 5 — The Ground Beneath You',
    body: 'Think about the last time you felt truly rooted. What were the conditions that made that possible?\n\nWas it a place? A person? A practice? A season of life? What does "rooted" feel like in your body, your spirit? And what tends to uproot you — and how long does it take to come back?',
    quote: 'The same rain that grows the tomatoes grows the weeds.',
    publishAt: '2026-01-01',
    tags: ['rootedness', 'stability', 'nature'],
  },
  {
    id: 'cp6',
    week: 0,
    chapter: 6,
    planId: 'main-plan',
    title: 'Chapter 6 — The Ask You\'re Afraid to Make',
    body: 'What are you afraid to ask for — and what does that fear tell you about what you actually want?\n\nSometimes we don\'t ask because we\'re afraid of the answer. Sometimes we\'re afraid of what the asking itself will reveal about us. Write into the fear. What\'s underneath it?',
    publishAt: '2026-01-01',
    tags: ['fear', 'desire', 'vulnerability'],
  },
  {
    id: 'cp7',
    week: 0,
    chapter: 7,
    planId: 'main-plan',
    title: 'Chapter 7 — What the Waiting Grew',
    body: 'Describe a season of waiting in your life. What grew in you during that time that couldn\'t have grown any other way?\n\nNot what you were waiting for — but what happened in you while you waited. What patience looked like. What it cost. And what, if anything, you\'re grateful for because of it.',
    publishAt: '2026-01-01',
    tags: ['waiting', 'patience', 'growth'],
  },
  {
    id: 'cp8',
    week: 0,
    chapter: 8,
    planId: 'main-plan',
    title: 'Chapter 8 — Someone Who Asked Well',
    body: 'Who in your life has modeled what it looks like to ask well? What did you learn from watching them?\n\nNot someone perfect — someone real. What made their way of asking different? Was it the words, the posture, the trust underneath it? What did they seem to know that you\'re still learning?',
    publishAt: '2026-01-01',
    tags: ['mentors', 'learning', 'prayer'],
  },
  {
    id: 'cp9',
    week: 0,
    chapter: 9,
    planId: 'main-plan',
    title: 'Chapter 9 — If the Asking Itself Mattered',
    body: 'What would change if you believed your asking mattered — not just the outcome, but the act itself?\n\nWhat if the prayer wasn\'t just a means to an end? What if showing up to ask was already something? How would you pray differently? How would you live differently?',
    publishAt: '2026-01-01',
    tags: ['prayer', 'presence', 'meaning'],
  },
  {
    id: 'cp10',
    week: 0,
    chapter: 10,
    planId: 'main-plan',
    title: 'Chapter 10 — Not Forgotten',
    body: 'Write about a moment when you felt forgotten. Then write about a moment when you knew you weren\'t.\n\nBoth are real. Both are true. What does it feel like to hold them together? And in the space between them — what have you come to believe about whether you are seen?',
    quote: 'I am not forgotten, and neither are you.',
    publishAt: '2026-01-01',
    tags: ['belonging', 'seen', 'faith'],
  },
]

export const allPrompts = [...weeklyPrompts, ...chapterPrompts]

export const sampleEntries: JournalEntry[] = [
  {
    id: 'e1',
    promptId: 'wp1',
    userId: 'u1',
    body: 'I realized I stopped imagining somewhere in my late twenties. Not all at once — more like a faucet that drips slower and slower until one day you notice it\'s completely off and you can\'t remember exactly when it stopped.\n\nThe last time I really let myself imagine freely was sitting on a back porch in Tennessee. I was 26. Nothing was figured out yet and somehow that felt like permission...',
    wordCount: 312,
    createdAt: '2026-06-02T09:14:00Z',
    updatedAt: '2026-06-02T09:52:00Z',
    isShared: false,
  },
  {
    id: 'e2',
    promptId: 'cp5',
    userId: 'u1',
    body: 'The last time I felt truly rooted was in my grandmother\'s garden. She never called it prayer, but I think it was...',
    wordCount: 187,
    createdAt: '2026-05-28T07:30:00Z',
    updatedAt: '2026-05-28T07:55:00Z',
    isShared: false,
  },
]

export const boardComments: BoardComment[] = [
  {
    id: 'bc1',
    promptId: 'wp2',
    userId: 'author',
    user: { id: 'author', name: 'The Author', role: 'author' },
    body: 'What strikes me every time I come back to this prompt is how much courage it takes to even write the dream down. The blank page before you type it is a kind of permission slip. If you\'re here — you\'ve already done the first brave thing.',
    createdAt: '2026-06-08T08:00:00Z',
    likes: 47,
    likedByCurrentUser: false,
    isPinned: true,
    replies: [],
  },
  {
    id: 'bc2',
    promptId: 'wp2',
    userId: 'u3',
    user: { id: 'u3', name: 'Jordan K.', role: 'reader' },
    body: 'I wrote "I want to write a children\'s book" for the first time in ten years. Just seeing it on the page made me cry a little. Thank you for this.',
    createdAt: '2026-06-08T10:22:00Z',
    likes: 34,
    likedByCurrentUser: true,
    replies: [
      {
        id: 'bc2r1',
        promptId: 'wp2',
        userId: 'author',
        user: { id: 'author', name: 'The Author', role: 'author' },
        body: 'Jordan — write the book. Please.',
        createdAt: '2026-06-08T11:05:00Z',
        likes: 22,
        likedByCurrentUser: false,
      },
    ],
  },
  {
    id: 'bc3',
    promptId: 'wp2',
    userId: 'u4',
    user: { id: 'u4', name: 'Mae R.', role: 'reader' },
    body: 'I realized the dream I gave up on wasn\'t a career or a place — it was a version of myself I stopped believing in. That felt like a lot to sit with on a Tuesday morning.',
    createdAt: '2026-06-08T12:44:00Z',
    likes: 28,
    likedByCurrentUser: false,
    replies: [],
  },
  {
    id: 'bc4',
    promptId: 'wp2',
    userId: 'u5',
    user: { id: 'u5', name: 'Thomas A.', role: 'reader' },
    body: 'Been reading for four weeks now and this is the first prompt that made me put the book down and just sit with it for a while before writing anything.',
    createdAt: '2026-06-08T14:10:00Z',
    likes: 19,
    likedByCurrentUser: false,
    replies: [],
  },
]

export const plans: Plan[] = [
  {
    id: 'main-plan',
    title: 'The Way of Asking',
    subtitle: '10 Chapters · 10 Prompts',
    description: 'The companion journal plan to the book. One prompt for each chapter — designed to be done slowly, one at a time, in whatever season you find yourself in.',
    type: 'evergreen',
    duration: 10,
    coverColor: 'sage',
    promptIds: chapterPrompts.map(p => p.id),
    enrolledCount: 1842,
    authorNote: 'These ten prompts are the ones I kept coming back to while writing the book. I hope they open something in you the way they opened something in me.',
    isEnrolled: true,
    progress: 40,
  },
  {
    id: 'live-june',
    title: 'Asking Together — June',
    subtitle: 'Live Plan · Starts June 15',
    description: 'A 21-day journey the author is doing alongside readers in real time. One prompt every two days. The author will share their own entries publicly on select days.',
    type: 'live',
    startDate: '2026-06-15',
    duration: 21,
    coverColor: 'bark',
    promptIds: ['wp1', 'wp2', 'wp3', 'wp4', 'cp1', 'cp2', 'cp3', 'cp4', 'cp5', 'cp6'],
    enrolledCount: 634,
    authorNote: 'I\'ll be doing this one with you. Some days I\'ll share what I wrote. Some days I won\'t. But I\'ll be in it.',
    isEnrolled: false,
  },
  {
    id: 'roots-plan',
    title: 'Learning to Stay',
    subtitle: 'Evergreen · 7 Days',
    description: 'A short practice on rootedness. Seven prompts about the ground beneath you — spiritual, emotional, physical. Good for any season.',
    type: 'evergreen',
    duration: 7,
    coverColor: 'moss',
    promptIds: ['cp5', 'wp4', 'cp7', 'cp9', 'cp10', 'wp1', 'cp6'],
    enrolledCount: 419,
    isEnrolled: false,
  },
]

export const feedPosts: FeedPost[] = [
  {
    id: 'fp1',
    userId: 'author',
    user: { id: 'author', name: 'The Author', role: 'author' },
    mediaType: 'long-text',
    body: 'The same rain that grows the tomatoes grows the weeds.\n\nI keep thinking about that. We want the conditions that produce growth to be selective — targeted. Only on the good stuff. But it doesn\'t work like that. The rain doesn\'t know the difference.\n\nMaybe that\'s the harder ask. Not "give me what I want" but "help me tend what shows up."',
    createdAt: '2026-06-07T09:00:00Z',
    likes: 213,
    likedByCurrentUser: false,
    comments: [
      {
        id: 'fc1',
        postId: 'fp1',
        userId: 'u3',
        user: { id: 'u3', name: 'Jordan K.', role: 'reader' },
        body: 'This is the line I keep coming back to this week.',
        createdAt: '2026-06-07T10:15:00Z',
        likes: 14,
        likedByCurrentUser: false,
      },
      {
        id: 'fc2',
        postId: 'fp1',
        userId: 'u4',
        user: { id: 'u4', name: 'Mae R.', role: 'reader' },
        body: '"Help me tend what shows up." I\'m writing that on my wall.',
        createdAt: '2026-06-07T11:40:00Z',
        likes: 31,
        likedByCurrentUser: true,
      },
    ],
  },
  {
    id: 'fp2',
    userId: 'u3',
    user: { id: 'u3', name: 'Jordan K.', role: 'reader' },
    mediaType: 'image',
    body: 'My journaling setup this morning. There\'s something about a good cup of tea and an honest question.',
    mediaUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80',
    createdAt: '2026-06-06T07:22:00Z',
    likes: 88,
    likedByCurrentUser: false,
    comments: [
      {
        id: 'fc3',
        postId: 'fp2',
        userId: 'author',
        user: { id: 'author', name: 'The Author', role: 'author' },
        body: 'The morning light in this photo. Yes.',
        createdAt: '2026-06-06T08:00:00Z',
        likes: 52,
        likedByCurrentUser: false,
      },
    ],
  },
  {
    id: 'fp3',
    userId: 'author',
    user: { id: 'author', name: 'The Author', role: 'author' },
    mediaType: 'short-text',
    body: 'You are not too late. You are not too much. You are not asking for too much.\n\nAsk anyway.',
    createdAt: '2026-06-05T08:30:00Z',
    likes: 341,
    likedByCurrentUser: true,
    comments: [],
  },
  {
    id: 'fp4',
    userId: 'u5',
    user: { id: 'u5', name: 'Thomas A.', role: 'reader' },
    mediaType: 'audio',
    body: 'Recorded a 4-minute reflection after finishing Chapter 5. Something about reading about roots while sitting in my actual garden made it click differently.',
    audioDuration: '4:12',
    createdAt: '2026-06-04T16:00:00Z',
    likes: 45,
    likedByCurrentUser: false,
    comments: [],
  },
  {
    id: 'fp5',
    userId: 'u6',
    user: { id: 'u6', name: 'Priya N.', role: 'reader' },
    mediaType: 'image',
    body: 'Found this in my grandmother\'s Bible. She underlined "Ask and it shall be given" in 1962. I\'ve been thinking about her a lot while reading this book.',
    mediaUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
    createdAt: '2026-06-03T14:22:00Z',
    likes: 172,
    likedByCurrentUser: false,
    comments: [
      {
        id: 'fc4',
        postId: 'fp5',
        userId: 'author',
        user: { id: 'author', name: 'The Author', role: 'author' },
        body: 'Priya, this is extraordinary. Thank you for sharing this.',
        createdAt: '2026-06-03T15:00:00Z',
        likes: 67,
        likedByCurrentUser: false,
      },
    ],
  },
]

export const authorQuotes = [
  'The same rain that grows the tomatoes grows the weeds.',
  'What if imagination isn\'t something we lose, but something that falls asleep?',
  'I am not forgotten, and neither are you.',
  'The way a cloud stretches across the sky… remind me that God is always moving.',
  'Maybe the goal was never to be remembered forever… maybe it was to live well right now.',
  'To love deeply. To eat good food. To drink something sweet. To laugh hard with the people right in front of us.',
  'You don\'t have to earn the asking.',
  'Ask anyway.',
]
